version: '3.7'

services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app/
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=secretsecret
      - SQL_DATABASE=hackernews
      - SQL_USER=hackernews
      - SQL_PASSWORD=hackernews
      - SQL_HOST=db
      - SQL_PORT=5432
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_USER=hackernews
      - POSTGRES_PASSWORD=hackernews
      - POSTGRES_DB=hackernews